on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
      - name: Install esy
        run: npm install -g esy
      - name: Create esy.json
        run: |
          echo ' \
            {\
              "name": "test", \
              "dependencies": { \
                "ocaml": "4.10.0" \
              } \
            } \
          ' > esy.json
      - name: Run esy action
        uses: wokalski/esy-github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.json') }}
      - name: Check if _esy exists
        run: stat _esy
